### ISSUE TITLE
arduino.mk does not work with Arduino 1.5.8 on 64 bit Linux

### ISSUE THREAD

**Issue by JobLeonard** [fsantanna/ceu-arduino#2]
I've also found the root problem on lines 126-129:

````
# check arduino software
ifeq ($(wildcard $(ARDUINODIR)/hardware/$(ARDUINOSUB)/boards.txt), )
$(error ARDUINODIR is not set correctly; arduino software not found)
endif
````

This test doesn't work any more because ````~/arduino-1.5.8/hardware/arduino/boards.txt```` does not exist in this version of Arduino. I can copy it from my 1.0.6 installation, of course, but that's not exactly a permanent solution.

**Comment by flippyhead** [comment]
I've tried making this change but now get:

```
ceu samples/blink1.ceu --out-c _ceu_app.src
touch poll.ino async.ino gd.ino
/opt/arduino/hardware/tools/avr/bin/avr-gcc  -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -fno-inline-small-functions -fno-jump-tables -mmcu=atmega328p -DF_CPU=16000000L -I. -Iutil -Iutility -I/opt/arduino/hardware/arduino/avr/cores/arduino -I/opt/arduino/hardware/arduino/avr/variants/standard/ -I/opt/arduino/libraries/LiquidCrystal  -I/opt/arduino/libraries/LiquidCrystal/utility -DARDUINO -Wno-pointer-arith  -c -o _arduino.a.tmp/hooks.o /opt/arduino/hardware/arduino/avr/cores/arduino/hooks.c
/opt/arduino/hardware/tools/avr/bin/avr-gcc: 1: /opt/arduino/hardware/tools/avr/bin/avr-gcc: Syntax error: "(" unexpected
make: *** [_arduino.a.tmp/hooks.o] Error 2
```

**Comment by fsantanna** [comment]
Looks like a misconfiguration in your `avr-gcc`.

I tried the command above (adjusting some paths) and it just works.
For instance, the line below compiles ok:
```
/opt/arduino-1.5.8/hardware/tools/avr/bin/avr-gcc -c -o hooks.o /opt/arduino-1.5.8/hardware/arduino/avr/cores/arduino/hooks.c
```

You might try to search your error message in Google or in the official Arduino forum.

**Comment by flippyhead** [comment]
Hmm OK. This is on the ceu in a virtual box package which seems to be pretty out of date (most apt-get packages I tried to install failed). I wonder if it could be related to something out of date avr-gcc needs. Though in this case the one being used is bundled directly in the arduino linux 64 download.

**Comment by fsantanna** [comment]
See #4 .
