### ISSUE TITLE
New version of Arduino IDE is out (1.6.6) - time to update?

### ISSUE THREAD

**Issue by JobLeonard** [fsantanna/ceu-arduino#4]
Just something you might want to have a look at:

> Today we are very proud to release Arduino IDE 1.6.6 and updated cores for all supported platforms (AVR 1.6.9, SAM 1.6.5, SAMD 1.6.2)
>
>This update brings an impressive 723 closed issues and 147 pull requests merged.
>
>Most intriguing features are:
>
>    Long-awaited new [arduino-builder](
https://github.com/arduino/arduino-builder): this is a pure command-line tool which takes care of mangling the code, resolving library dependencies and setting up the compilation units. It can also be used as a standalone program in a continuous-integration environment

https://blog.arduino.cc/2015/11/03/arduino-ide-1-6-6-released-and-available-for-download/

That arduino-builder might be nice, although it is made for Arduino sketches so I don't know if it can work with C code (let alone C code generated by Céu).

**Comment by fsantanna** [comment]
That's great, thanks!
Probably much better than the handmade `Makefile` we currently use.

**Comment by fsantanna** [comment]
Done (and now required!)
